version: "3"

services:
  api:
    build: ./
    volumes:
       - .:/app/src
    image: scone-api
    command:  uvicorn main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    network_mode: "host"
